# Generated by Django 3.0.10 on 2022-05-09 15:57

from django.db import migrations, models
import shortner_app.utils


class Migration(migrations.Migration):

    dependencies = [
        ('shortner_app', '0002_auto_20220509_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlshort',
            name='id',
        ),
        migrations.AlterField(
            model_name='urlshort',
            name='alias',
            field=models.CharField(default=shortner_app.utils.generate_random_alias, max_length=8, primary_key=True, serialize=False),
        ),
    ]
